language: node_js

sudo: required

node_js: 
  - 12  

cache:
  directories:
    - node_modules

branches:
  only:
    - src

before_install:
  - npm install -g hexo-cli
# Start: Build Lifecycle
install:
  - npm install --save-dev hexo-render-pug hexo-renderer-stylus
  - npm install
  - npm install hexo-deployer-git --save
  
script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "bclin717"
  - git config user.email "bclin@gmail.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
# End: Build LifeCycle
